### PR TITLE
new event blacklist

### PR DESCRIPTION
**Pull request by Prizmagnetic**
replaces #24

### CODE REVIEW

**Comment by kennethjiang** [comment]
@Prizmagnetic Thank you for contributing to TSD! I just pushed a commit https://github.com/TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective/commit/6ea4ca8e531a0cccd8e3fdef0d562f2eb0454f42 that did similar thing to this PR but in a slightly different way (I basically just whitelisted `Print*` events).

It'll be great if you can test with the code in master and see if everything works. Also let me know if you think black list is preferable than white list.

**Comment by Prizmagnetic** [comment]
I think we want events like "Error" , "Startup"  and a few more odd ones to go through, and since they aren't triggered often, they wont cause any problems

**Comment by kennethjiang** [comment]
I can see how "Error" or "Startup" may be useful in the future. Can you see how these events can help us for now?

**Comment by kennethjiang** [comment]
Closing this PR as it is included in 0.6.1

**Pull request closed without merging**
