### PR TITLE
Support for utf8 filenames for uploads

### PR DESCRIPTION
**Pull request by encetamasb**
Original filename is kept for "displaying".

Added explicit numbering routine to have unique pathes,
what's necessary when overwrite is not allowed.

### CODE REVIEW

**Comment by kennethjiang** [comment]
@encetamasb Sorry I won't have time to review this PR. can you merge it to `dev` (not `master`) and do some testing? Not sure if it needs to be backward compatible but please think about it too. We don't want to break old plugin versions. Breaking the old servers is fine as most TSD private server owners know they only need to upgrade the server code

**Comment by encetamasb** [comment]
> Not sure if it needs to be backward compatible but please think about it too. We don't want to break old plugin versions. 

It's backward compatible with older server versions, I don't see issue there. 

Which octoprint versions do we support? Instead of writing file directly to the target folder, I use an internal api of octoprint (octoprint.server.fileManager.add_file). This call updates related metadata too, so original file name is kept even if the filename get sanitized (utf8->ascii). This works in recent octoprint versions. How far should I go back and test compatibility?

**Comment by encetamasb** [comment]
Added fixes for  py2.
Matched the file-renaming logic the way octoprint does it (<origname>_<copy number>.gcode).
Targeting dev.

**Comment by encetamasb** [comment]
> This works in recent octoprint versions. How far should I go back and test compatibility?

Tested 1.5.0, 1.6.1 and 1.7.0rc2. It works well in these versions. I skipped 1.4.0 as that does not has virtual printer as far as I see.

**Pull request merged**
